# Generated by Django 4.2.29 on 2026-03-18 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_feedback_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentimanetAnalyze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('positive_val', models.FloatField()),
                ('negative_val', models.FloatField()),
                ('neutral_val', models.FloatField()),
                ('value', models.FloatField()),
                ('meta_data', models.JSONField(blank=True, null=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='users.feedback')),
            ],
        ),
    ]
