# Generated by Django 4.2.29 on 2026-04-03 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_company_employeeprofile_platforms_delete_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='users.company'),
            preserve_default=False,
        ),
    ]
