# Generated by Django 4.2.29 on 2026-04-06 10:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_feedback_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название платформы')),
                ('code', models.SlugField(unique=True, verbose_name='Системный код')),
                ('base_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='Базовый URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Платформа',
                'verbose_name_plural': 'Платформы',
            },
        ),
        migrations.DeleteModel(
            name='Platforms',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='source_id',
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AddField(
            model_name='feedback',
            name='platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feedbacks', to='users.platform'),
        ),
    ]
