# Generated by Django 4.2.29 on 2026-04-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_platform_delete_platforms_remove_feedback_source_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentAnchor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Якорь (фраза/слово)')),
                ('sentiment', models.CharField(choices=[('POSITIVE', 'Позитивный'), ('NEGATIVE', 'Негативный')], max_length=15, verbose_name='Тональность')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'Английский')], default='ru', max_length=5, verbose_name='Язык')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Словарный якорь',
                'verbose_name_plural': 'Словарные якоря',
                'unique_together': {('text', 'language')},
            },
        ),
    ]
