# Generated by Django 4.2.29 on 2026-04-15 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0012_remove_employeeprofile_company_companymember_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentimanetanalyze',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_sentiments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sentimanetanalyze',
            name='is_manual',
            field=models.BooleanField(default=False, verbose_name='Ручная правка'),
        ),
    ]
