# Generated by Django 4.2.29 on 2026-04-20 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_in_app_enabled', models.BooleanField(default=True, verbose_name='Внутренние уведомления (Колокольчик)')),
                ('is_telegram_enabled', models.BooleanField(default=False, verbose_name='Уведомления в Telegram')),
                ('is_email_enabled', models.BooleanField(default=False, verbose_name='Уведомления в Email')),
                ('critical_threshold', models.FloatField(default=-0.5, verbose_name='Порог критического негатива')),
                ('telegram_chat_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Telegram чата клиента')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='users.company')),
            ],
            options={
                'verbose_name': 'Настройки уведомлений',
                'verbose_name_plural': 'Настройки уведомлений',
            },
        ),
    ]
