# Generated by Django 4.2.29 on 2026-04-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_notificationsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsetting',
            name='alert_template',
            field=models.TextField(blank=True, help_text='Доступные переменные: {company}, {platform}, {score}, {text}, {link}', null=True, verbose_name='Шаблон уведомления'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='custom_emails',
            field=models.TextField(blank=True, help_text='Укажите email-адреса через запятую (например: boss@mail.ru, qc@mail.ru)', null=True, verbose_name='Дополнительные Email'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='telegram_bot_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Токен Telegram бота клиента'),
        ),
        migrations.AlterField(
            model_name='notificationsetting',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Telegram чата'),
        ),
    ]
