# Generated by Django 4.2.29 on 2026-04-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_notificationsetting_alert_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на источник'),
        ),
    ]
